11

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,17 +27,17 @@ jobs:
       - name: Make mvnw Executable
         run: chmod +x mvnw
 
-      - name: Build Application and Docker Image
-        run: ./mvnw -Pprod verify jib:dockerBuild -DskipTests -Dmaven.javadoc.skip=true -DskipITs -C
+      # - name: Build Application and Docker Image
+      #   run: ./mvnw -Pprod verify jib:dockerBuild -DskipTests -Dmaven.javadoc.skip=true -DskipITs -C
 
-      - name: Verify Dockerfile
-        run: |
-          if [ -f Dockerfile ]; then
-            echo "Dockerfile found!"
-          else
-            echo "ERROR: Dockerfile not found!"
-            exit 1
-          fi
+      # - name: Verify Dockerfile
+      #   run: |
+      #     if [ -f Dockerfile ]; then
+      #       echo "Dockerfile found!"
+      #     else
+      #       echo "ERROR: Dockerfile not found!"
+      #       exit 1
+      #     fi
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -58,16 +58,16 @@ jobs:
           docker tag itstrat:latest $ECR_REGISTRY/itstrat:latest
           docker push $ECR_REGISTRY/itstrat:latest
 
-      - name: Build and Push Docker Images
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: harish  # Update to match your ECR repo
-          IMAGE_TAG: latest
-        run: |
-          echo "Building Docker image..."
-          docker build -t 637423430820.dkr.ecr.us-east-1.amazonaws.com/harish:latest .
-          echo "Pushing Docker image..."
-          docker push 637423430820.dkr.ecr.us-east-1.amazonaws.com/harish:latest
+      # - name: Build and Push Docker Images
+      #   env:
+      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #     ECR_REPOSITORY: harish  # Update to match your ECR repo
+      #     IMAGE_TAG: latest
+      #   run: |
+      #     echo "Building Docker image..."
+      #     docker build -t 637423430820.dkr.ecr.us-east-1.amazonaws.com/harish:latest .
+      #     echo "Pushing Docker image..."
+      #     docker push 637423430820.dkr.ecr.us-east-1.amazonaws.com/harish:latest
 
       - name: Set Up kubectl
         run: |
